apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  params:
    - name: pathToDockerFile
      type: string
      default: Dockerfile
    - name: pathToContext
      type: string
      default: $(resources.inputs.source.path)
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: image 
        type: image
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: "DOCKER_CONFIG"
          value: "/root/.docker"
      command:
      - /kaniko/executor
      args:
      - --context=$(params.pathToContext)
      - --dockerfile=$(params.pathToDockerFile)
      - --destination=$(resources.outputs.corpora-image.url)
