name             = "bryan"
key_name         = "lab-key"
private_key_path = "./ssh/id_rsa"
public_key_path  = "./ssh/id_rsa.pub"
bastion_type     = "t3.2xlarge"
owner            = "bryan"
project          = "k3s-lab"
env              = "dev"
