curl -s localhost:30000/corpora/animals/ant_anatomy
curl -s localhost:30000/corpora/animals/birds_antarctica
curl -s localhost:30000/corpora/animals/birds_north_america
curl -s localhost:30000/corpora/animals/cats
curl -s localhost:30000/corpora/animals/cephalopod_anatomy
curl -s localhost:30000/corpora/animals/collateral_adjectives
curl -s localhost:30000/corpora/animals/common
curl -s localhost:30000/corpora/animals/dinosaurs
curl -s localhost:30000/corpora/animals/dogs
curl -s localhost:30000/corpora/animals/dog_names
curl -s localhost:30000/corpora/animals/donkeys
curl -s localhost:30000/corpora/animals/horses
curl -s localhost:30000/corpora/animals/ponies
curl -s localhost:30000/corpora/animals/rabbits
curl -s localhost:30000/corpora/archetypes/artifact
curl -s localhost:30000/corpora/archetypes/character
curl -s localhost:30000/corpora/archetypes/event
curl -s localhost:30000/corpora/archetypes/setting
curl -s localhost:30000/corpora/architecture/passages
curl -s localhost:30000/corpora/architecture/rooms
curl -s localhost:30000/corpora/art/isms
curl -s localhost:30000/corpora/books/academic_subjects
curl -s localhost:30000/corpora/books/bestsellers
curl -s localhost:30000/corpora/colors/crayola
curl -s localhost:30000/corpora/colors/dulux
curl -s localhost:30000/corpora/colors/google_material_colors
curl -s localhost:30000/corpora/colors/paints
curl -s localhost:30000/corpora/colors/palettes
curl -s localhost:30000/corpora/colors/web_colors
curl -s localhost:30000/corpora/colors/wikipedia
curl -s localhost:30000/corpora/colors/xkcd
curl -s localhost:30000/corpora/corporations/cars
curl -s localhost:30000/corpora/corporations/charities
curl -s localhost:30000/corpora/corporations/djia
curl -s localhost:30000/corpora/corporations/fortune500
curl -s localhost:30000/corpora/corporations/industries
curl -s localhost:30000/corpora/corporations/nasdaq
curl -s localhost:30000/corpora/corporations/newspapers
curl -s localhost:30000/corpora/divination/tarot_interpretations
curl -s localhost:30000/corpora/divination/zodiac
curl -s localhost:30000/corpora/film-tv/game-of-thrones-houses
curl -s localhost:30000/corpora/film-tv/iab_categories
curl -s localhost:30000/corpora/film-tv/look-around-you-shakespeare
curl -s localhost:30000/corpora/film-tv/netflix-categories
curl -s localhost:30000/corpora/film-tv/popular-movies
curl -s localhost:30000/corpora/film-tv/tv_shows
curl -s localhost:30000/corpora/film-tv/Westworld_quotes
curl -s localhost:30000/corpora/foods/apple_cultivars
curl -s localhost:30000/corpora/foods/bad_beers
curl -s localhost:30000/corpora/foods/beer_categories
curl -s localhost:30000/corpora/foods/beer_styles
curl -s localhost:30000/corpora/foods/breads_and_pastries
curl -s localhost:30000/corpora/foods/combine
curl -s localhost:30000/corpora/foods/condiments
curl -s localhost:30000/corpora/foods/curds
curl -s localhost:30000/corpora/foods/fruits
curl -s localhost:30000/corpora/foods/herbs_n_spices
curl -s localhost:30000/corpora/foods/hot_peppers
curl -s localhost:30000/corpora/foods/iba_cocktails
curl -s localhost:30000/corpora/foods/menuItems
curl -s localhost:30000/corpora/foods/pizzaToppings
curl -s localhost:30000/corpora/foods/sandwiches
curl -s localhost:30000/corpora/foods/sausages
curl -s localhost:30000/corpora/foods/scotch_whiskey
curl -s localhost:30000/corpora/foods/tea
curl -s localhost:30000/corpora/foods/vegetables
curl -s localhost:30000/corpora/foods/vegetable_cooking_times
curl -s localhost:30000/corpora/foods/wine_descriptions
curl -s localhost:30000/corpora/games/bannedGames/argentina/bannedList
curl -s localhost:30000/corpora/games/bannedGames/brazil/bannedList
curl -s localhost:30000/corpora/games/bannedGames/china/bannedList
curl -s localhost:30000/corpora/games/bannedGames/denmark/bannedList
curl -s localhost:30000/corpora/games/bannedGames/germany/bannedList
curl -s localhost:30000/corpora/games/bannedGames/saudi_arabia/bannedList
curl -s localhost:30000/corpora/games/board_games
curl -s localhost:30000/corpora/games/cluedo
curl -s localhost:30000/corpora/games/dark_souls_iii_messages
curl -s localhost:30000/corpora/games/jeopardy_questions
curl -s localhost:30000/corpora/games/League_of_legends_champion_names
curl -s localhost:30000/corpora/games/pokemon
curl -s localhost:30000/corpora/games/rpg/rpg_designers
curl -s localhost:30000/corpora/games/rpg/rpg_games
curl -s localhost:30000/corpora/games/rpg/rpg_settings
curl -s localhost:30000/corpora/games/scrabble
curl -s localhost:30000/corpora/games/street_fighter_ii
curl -s localhost:30000/corpora/games/trivial_pursuit
curl -s localhost:30000/corpora/games/wrestling_moves
curl -s localhost:30000/corpora/games/zelda
curl -s localhost:30000/corpora/geography/anthropogenic_features
curl -s localhost:30000/corpora/geography/canada_provinces_and_territories
curl -s localhost:30000/corpora/geography/canadian_municipalities
curl -s localhost:30000/corpora/geography/countries
curl -s localhost:30000/corpora/geography/countries_with_capitals
curl -s localhost:30000/corpora/geography/english_towns_cities
curl -s localhost:30000/corpora/geography/environmental_hazards
curl -s localhost:30000/corpora/geography/geographic_features
curl -s localhost:30000/corpora/geography/japanese_prefectures
curl -s localhost:30000/corpora/geography/london_underground_stations
curl -s localhost:30000/corpora/geography/nationalities
curl -s localhost:30000/corpora/geography/norwegian_cities
curl -s localhost:30000/corpora/geography/nyc_neighborhood_zips
curl -s localhost:30000/corpora/geography/oceans
curl -s localhost:30000/corpora/geography/rivers
curl -s localhost:30000/corpora/geography/sf_neighborhoods
curl -s localhost:30000/corpora/geography/us_airport_codes
curl -s localhost:30000/corpora/geography/us_cities
curl -s localhost:30000/corpora/geography/us_counties
curl -s localhost:30000/corpora/geography/us_metropolitan_areas
curl -s localhost:30000/corpora/geography/us_state_capitals
curl -s localhost:30000/corpora/geography/venues
curl -s localhost:30000/corpora/geography/winds
curl -s localhost:30000/corpora/governments/governmentForms
curl -s localhost:30000/corpora/governments/mass-surveillance-project-names
curl -s localhost:30000/corpora/governments/nsa_projects
curl -s localhost:30000/corpora/governments/uk_political_parties
curl -s localhost:30000/corpora/governments/us_federal_agencies
curl -s localhost:30000/corpora/governments/us_mil_operations
curl -s localhost:30000/corpora/humans/2016_us_presidential_candidates
curl -s localhost:30000/corpora/humans/atus_activities
curl -s localhost:30000/corpora/humans/authors
curl -s localhost:30000/corpora/humans/bodyParts
curl -s localhost:30000/corpora/humans/britishActors
curl -s localhost:30000/corpora/humans/celebrities
curl -s localhost:30000/corpora/humans/descriptions
curl -s localhost:30000/corpora/humans/englishHonorifics
curl -s localhost:30000/corpora/humans/familyRelations
curl -s localhost:30000/corpora/humans/famousDuos
curl -s localhost:30000/corpora/humans/firstNames
curl -s localhost:30000/corpora/humans/genders
curl -s localhost:30000/corpora/humans/lastNames
curl -s localhost:30000/corpora/humans/moods
curl -s localhost:30000/corpora/humans/norwayFirstNamesBoys
curl -s localhost:30000/corpora/humans/norwayFirstNamesGirls
curl -s localhost:30000/corpora/humans/norwayLastNames
curl -s localhost:30000/corpora/humans/occupations
curl -s localhost:30000/corpora/humans/prefixes
curl -s localhost:30000/corpora/humans/richpeople
curl -s localhost:30000/corpora/humans/scientists
curl -s localhost:30000/corpora/humans/spanishFirstNames
curl -s localhost:30000/corpora/humans/spanishLastNames
curl -s localhost:30000/corpora/humans/spinalTapDrummers
curl -s localhost:30000/corpora/humans/suffixes
curl -s localhost:30000/corpora/humans/thirdPersonPronouns
curl -s localhost:30000/corpora/humans/tolkienCharacterNames
curl -s localhost:30000/corpora/humans/us_presidents
curl -s localhost:30000/corpora/humans/wrestlers
curl -s localhost:30000/corpora/instructions/laundry_care
curl -s localhost:30000/corpora/materials/abridged-body-fluids
curl -s localhost:30000/corpora/materials/building-materials
curl -s localhost:30000/corpora/materials/carbon-allotropes
curl -s localhost:30000/corpora/materials/decorative-stones
curl -s localhost:30000/corpora/materials/fabrics
curl -s localhost:30000/corpora/materials/fibers
curl -s localhost:30000/corpora/materials/fictional-materials
curl -s localhost:30000/corpora/materials/gemstones
curl -s localhost:30000/corpora/materials/layperson-metals
curl -s localhost:30000/corpora/materials/metals
curl -s localhost:30000/corpora/materials/natural-materials
curl -s localhost:30000/corpora/materials/packaging
curl -s localhost:30000/corpora/materials/plastic-brands
curl -s localhost:30000/corpora/materials/sculpture-materials
curl -s localhost:30000/corpora/materials/technical-fabrics
curl -s localhost:30000/corpora/mathematics/fibonnaciSequence
curl -s localhost:30000/corpora/mathematics/primes
curl -s localhost:30000/corpora/mathematics/primes_binary
curl -s localhost:30000/corpora/mathematics/trigonometry
curl -s localhost:30000/corpora/medicine/cancer
curl -s localhost:30000/corpora/medicine/diagnoses
curl -s localhost:30000/corpora/medicine/diseases
curl -s localhost:30000/corpora/medicine/drugNameStems
curl -s localhost:30000/corpora/medicine/drugs
curl -s localhost:30000/corpora/medicine/hospitals
curl -s localhost:30000/corpora/medicine/infectious_diseases
curl -s localhost:30000/corpora/medicine/symptoms
curl -s localhost:30000/corpora/music/a_list_of_guitar_manufacturers
curl -s localhost:30000/corpora/music/bands_that_have_opened_for_tool
curl -s localhost:30000/corpora/music/female_classical_guitarists
curl -s localhost:30000/corpora/music/genres
curl -s localhost:30000/corpora/music/hamilton_musical_obcrecording_actors_characters
curl -s localhost:30000/corpora/music/instruments
curl -s localhost:30000/corpora/music/mtv_day_one
curl -s localhost:30000/corpora/music/rock_hall_of_fame
curl -s localhost:30000/corpora/music/xxl_freshman
curl -s localhost:30000/corpora/mythology/egyptian_gods
curl -s localhost:30000/corpora/mythology/greek_gods
curl -s localhost:30000/corpora/mythology/greek_monsters
curl -s localhost:30000/corpora/mythology/greek_myths_master
curl -s localhost:30000/corpora/mythology/greek_titans
curl -s localhost:30000/corpora/mythology/hebrew_god
curl -s localhost:30000/corpora/mythology/lovecraft
curl -s localhost:30000/corpora/mythology/monsters
curl -s localhost:30000/corpora/mythology/norse_gods
curl -s localhost:30000/corpora/mythology/roman_deities
curl -s localhost:30000/corpora/objects/clothing
curl -s localhost:30000/corpora/objects/corpora_winners
curl -s localhost:30000/corpora/objects/objects
curl -s localhost:30000/corpora/plants/cannabis
curl -s localhost:30000/corpora/plants/flowers
curl -s localhost:30000/corpora/plants/plants
curl -s localhost:30000/corpora/religion/christian_saints
curl -s localhost:30000/corpora/religion/fictional_religions
curl -s localhost:30000/corpora/religion/parody_religions
curl -s localhost:30000/corpora/religion/religions
curl -s localhost:30000/corpora/science/elements
curl -s localhost:30000/corpora/science/hail_size
curl -s localhost:30000/corpora/science/minor_planets
curl -s localhost:30000/corpora/science/planets
curl -s localhost:30000/corpora/science/pregnancy
curl -s localhost:30000/corpora/science/toxic_chemicals
curl -s localhost:30000/corpora/science/weather_conditions
curl -s localhost:30000/corpora/societies_and_groups/animal_welfare
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/australia
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/canada
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/china
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/egypt
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/european_union
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/india
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/iran
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/israel
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/kazakhstan
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/russia
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/saudi_arabia
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/tunisia
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/turkey
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/ukraine
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/united_arab_emirates
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/united_kingdom
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/united_nations
curl -s localhost:30000/corpora/societies_and_groups/designated_terrorist_groups/united_states
curl -s localhost:30000/corpora/societies_and_groups/fraternities/coeducational_fraternities
curl -s localhost:30000/corpora/societies_and_groups/fraternities/defunct
curl -s localhost:30000/corpora/societies_and_groups/fraternities/fraternities
curl -s localhost:30000/corpora/societies_and_groups/fraternities/professional
curl -s localhost:30000/corpora/societies_and_groups/fraternities/service
curl -s localhost:30000/corpora/societies_and_groups/fraternities/sororities
curl -s localhost:30000/corpora/societies_and_groups/semi_secret
curl -s localhost:30000/corpora/sports/football/epl_teams
curl -s localhost:30000/corpora/sports/football/laliga_teams
curl -s localhost:30000/corpora/sports/football/serieA
curl -s localhost:30000/corpora/sports/mlb_teams
curl -s localhost:30000/corpora/sports/nba_mvps
curl -s localhost:30000/corpora/sports/nba_teams
curl -s localhost:30000/corpora/sports/nfl_teams
curl -s localhost:30000/corpora/sports/nhl_teams
curl -s localhost:30000/corpora/sports/olympics
curl -s localhost:30000/corpora/sports/sports
curl -s localhost:30000/corpora/technology/appliances
curl -s localhost:30000/corpora/technology/computer_sciences
curl -s localhost:30000/corpora/technology/fireworks
curl -s localhost:30000/corpora/technology/guns_n_rifles
curl -s localhost:30000/corpora/technology/knots
curl -s localhost:30000/corpora/technology/lisp
curl -s localhost:30000/corpora/technology/new_technologies
curl -s localhost:30000/corpora/technology/photo_sharing_websites
curl -s localhost:30000/corpora/technology/programming_languages
curl -s localhost:30000/corpora/technology/programming_languages_popular
curl -s localhost:30000/corpora/technology/social_networking_websites
curl -s localhost:30000/corpora/technology/video_hosting_websites
curl -s localhost:30000/corpora/transportation/commercial-aircraft
curl -s localhost:30000/corpora/travel/lcc
curl -s localhost:30000/corpora/words/adjs
curl -s localhost:30000/corpora/words/adverbs
curl -s localhost:30000/corpora/words/closed_pairs
curl -s localhost:30000/corpora/words/common
curl -s localhost:30000/corpora/words/compounds
curl -s localhost:30000/corpora/words/crash_blossoms
curl -s localhost:30000/corpora/words/eggcorns
curl -s localhost:30000/corpora/words/emoji/codePage437
curl -s localhost:30000/corpora/words/emoji/cute_kaomoji
curl -s localhost:30000/corpora/words/emoji/emoji
curl -s localhost:30000/corpora/words/encouraging_words
curl -s localhost:30000/corpora/words/ergative_verbs
curl -s localhost:30000/corpora/words/expletives
curl -s localhost:30000/corpora/words/harvard_sentences
curl -s localhost:30000/corpora/words/infinitive_verbs
curl -s localhost:30000/corpora/words/interjections
curl -s localhost:30000/corpora/words/literature/infinitejest
curl -s localhost:30000/corpora/words/literature/lovecraft_words
curl -s localhost:30000/corpora/words/literature/mr_men_little_miss
curl -s localhost:30000/corpora/words/literature/shakespeare_phrases
curl -s localhost:30000/corpora/words/literature/shakespeare_sonnets
curl -s localhost:30000/corpora/words/literature/shakespeare_words
curl -s localhost:30000/corpora/words/literature/technology_quotes
curl -s localhost:30000/corpora/words/nouns
curl -s localhost:30000/corpora/words/oprah_quotes
curl -s localhost:30000/corpora/words/personal_nouns
curl -s localhost:30000/corpora/words/personal_pronouns
curl -s localhost:30000/corpora/words/possessive_pronouns
curl -s localhost:30000/corpora/words/prefix_root_suffix
curl -s localhost:30000/corpora/words/prepositions
curl -s localhost:30000/corpora/words/proverbs
curl -s localhost:30000/corpora/words/resume_action_words
curl -s localhost:30000/corpora/words/rhymeless_words
curl -s localhost:30000/corpora/words/spells
curl -s localhost:30000/corpora/words/states_of_drunkenness
curl -s localhost:30000/corpora/words/state_verbs
curl -s localhost:30000/corpora/words/stopwords/ar
curl -s localhost:30000/corpora/words/stopwords/bg
curl -s localhost:30000/corpora/words/stopwords/cs
curl -s localhost:30000/corpora/words/stopwords/da
curl -s localhost:30000/corpora/words/stopwords/de
curl -s localhost:30000/corpora/words/stopwords/en
curl -s localhost:30000/corpora/words/stopwords/es
curl -s localhost:30000/corpora/words/stopwords/fi
curl -s localhost:30000/corpora/words/stopwords/fr
curl -s localhost:30000/corpora/words/stopwords/gr
curl -s localhost:30000/corpora/words/stopwords/it
curl -s localhost:30000/corpora/words/stopwords/jp
curl -s localhost:30000/corpora/words/stopwords/lv
curl -s localhost:30000/corpora/words/stopwords/nl
curl -s localhost:30000/corpora/words/stopwords/no
curl -s localhost:30000/corpora/words/stopwords/pl
curl -s localhost:30000/corpora/words/stopwords/pt
curl -s localhost:30000/corpora/words/stopwords/ru
curl -s localhost:30000/corpora/words/stopwords/sk
curl -s localhost:30000/corpora/words/stopwords/sv
curl -s localhost:30000/corpora/words/stopwords/tr
curl -s localhost:30000/corpora/words/strange_words
curl -s localhost:30000/corpora/words/units_of_time
curl -s localhost:30000/corpora/words/us_president_quotes
curl -s localhost:30000/corpora/words/verbs
curl -s localhost:30000/corpora/words/verbs_with_conjugations
curl -s localhost:30000/corpora/words/word_clues/clues_five
curl -s localhost:30000/corpora/words/word_clues/clues_four
curl -s localhost:30000/corpora/words/word_clues/clues_six
